### ISSUE TITLE
Number of lines when default arguments include a "{"

### ISSUE THREAD

**Issue by edward-burn** [darwin-eu-dev/PaRe#14]
@mvankessel-EMC There are a small number of functions that include "}" somewhere in their default arguments. For example, [glue::glue_data](https://glue.tidyverse.org/reference/glue.html) has this as the default for .close. In these edge cases I think we have a bug where we see this being the point at which the function ends

```
glue_data(
  .x,
  ...,
  .sep = "",
  .envir = [parent.frame](https://rdrr.io/r/base/sys.parent.html)(),
  .open = "{",
  .close = "}",
  .na = "NA",
  .null = [character](https://rdrr.io/r/base/character.html)(),
  .comment = "#",
  .literal = FALSE,
  .transformer = identity_transformer,
  .trim = TRUE
)
```

Current PaRe results for glue_data
```
library(PaRe)
PaRe::getDefinedFunctionsPkg(here::here("inst", "glue")) %>% 
  dplyr::filter(fun == "glue_data")
# file start size       fun nArgs cycloComp
# 1 glue.R    87    0 glue_data     5        NA
```

**Comment by mvankessel-EMC** [comment]
@edward-burn Thanks for the report. I've just pushed a change (48040860d49247d44c8d775f025103c90f73f772) so the number of braces `(` and `)` have to be equal.



Which gives the following output:
```
defFuns <- getDefinedFunctionsPkg(path = "inst/glue/")

defFuns %>%
  filter(fun == "glue_data")

>    file start size       fun nArgs cycloComp
>1 glue.R    88  112 glue_data     8        19
```

Note that the start of the body of the function is now line 88 instead of 87, and the cyclomatic complexity is no longer NA.

Let me know if you other bugs, with the new implementation.

I'll leave the issue open for now for any follow up.

**Comment by edward-burn** [comment]
Great! Let me see if I can find any other examples and I'll report back here
